image: python:3

test:
  script:
  - ./test.cmd

push-to-heroku:
  only:
  - master
  script:
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/stackchat-dev.git
  - git push -f heroku master

