image: python:3

test:
  stage: testing
  script:
  - pip install pipenv -q
  - pipenv install --dev
  - pipenv run python -m stackchat version
  - pipenv run python -m pytest -v

install:
  stage: testing
  script:
  - pip install .
  - stack.chat version

heroku:
  stage: deploy
  image: ruby:2.2
  script:
  - gem install dpl
  - dpl --provider=heroku --app=stackchat-dev --api-key=$HEROKU_API_KEY
  only:
  - master
